apiVersion: v1
kind: Service
metadata:
  name: spring-starbucks-client-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081 
  selector:
    name: spring-starbucks-client


